version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/data/db
    container_name: petcatalog-db-dev

  server:
    image: petcatalog-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    environment:
      - DOG_API_KEY=${DOG_API_KEY}
      - CAT_API_KEY=${CAT_API_KEY}
      - DATABASE_URL_DEV=postgres://postgres:example@db:5432/postgres
    container_name: petcatalog-backend-dev
    depends_on:
      - db

  migration:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command:
      [
        './wait-for-it/wait-for-it.sh',
        'db:5432',
        '--',
        'npm',
        'run',
        'migration:up'
      ]
    links:
      - db
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL_DEV=postgres://postgres:example@db:5432/postgres
    container_name: petcatalog-migration-dev
  debug-helper:
    image: busybox
