DELETE  http://localhost:3001/api/dogapi/favorites/94347 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlckBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzEzMzE0MTk2fQ.jibA07xG8LsEU5E4kSlMQRy_c4Ir8oorBup-3lHXluQ
content-type: application/json
